### ISSUE TITLE
Getting the cronHistory.find()

### ISSUE THREAD

**Issue by binarytracer** [percolatestudio/meteor-synced-cron#100]
is there a way i could get the cursor from the collection as `cronHistory.find()` and use that  on publication?  that somewhat similar below

```javascript
Meteor.publish("jobList", function(){
return cronHistory.find();
});
```

When i try to defined its collection 
```js
const Jobs = new Mongo.Collection("cronHistory");
return default Jobs;
```
i got these on server log 

```js

W20160607-16:33:27.537(8)? (STDERR) Error: A method named '/cronHistory/insert' is already defined
W20160607-16:33:27.537(8)? (STDERR)     at packages/ddp-server/livedata_server.js:1548:15
W20160607-16:33:27.537(8)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20160607-16:33:27.537(8)? (STDERR)     at Server.methods (packages/ddp-server/livedata_server.js:1544:7)
W20160607-16:33:27.537(8)? (STDERR)     at packages/allow-deny/allow-deny.js:191:24
...

```

**Comment by BradRyan** [comment]
Try using referencing SyncedCron._collection instead of creating a new collection.

https://github.com/percolatestudio/meteor-synced-cron/blob/master/synced-cron-server.js

**Comment by binarytracer** [comment]
@BradRyan, ive tried that already but seems that `property` is not available, ive tried that on server-side.
