### ISSUE TITLE
HTTP.get in synced fron return LEAF error

### ISSUE THREAD

**Issue by Neobii** [percolatestudio/meteor-synced-cron#101]
I put HTTP.get in a job and got this cryptic error:

`SyncedCron: Exception "Get streaming informaiton" Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE`

**Comment by TheGame2500** [comment]
I don't think it's related to synced cron. If you're making an API call you probably messed up it's key. Could you give more details?

**Comment by Neobii** [comment]
I'm calling from the listen to my radio, it works fine if I put it in a try
catch block.  It returns a status code 200 from the api call though.

**Comment by TheGame2500** [comment]
@Neobii could you try running the code without try/catch blocks outside of synced cron and see if it works? Thanks.
PS: Could you clarify what "I'm calling from the listen to my radio" I don't really understand what you mean.

**Comment by Neobii** [comment]
Without the try, catch blocks, after the HTTP call, the LEAF error pops up
that I previously mentioned.  I'm making an HTTP call to the
http://www.listen2myradio.com/ data api.

**Comment by TheGame2500** [comment]
@Neobii , well if you ran the code outside synced cron and the error still pops up, it's not a synced cron issue. You should google the error. Some interesting results pop up.

**Comment by Neobii** [comment]
This is gist https://gist.github.com/Neobii/5026b27e243bb897a619710f994d7c9d

**Comment by TheGame2500** [comment]
@Neobii yes, ok I get it, but please try running the HTTP call outside of Synced Cron and see if it works.

**Comment by Neobii** [comment]
Cool thanks, I see, I thought it was a little fishy :).
