### ISSUE TITLE
Scaling CPU intensive cron jobs - dedicated server for Cron?

### ISSUE THREAD

**Issue by niranjans** [percolatestudio/meteor-synced-cron#103]
We have 3 production servers (DigitalOcean) running our Meteor app (Using Mupx, Cluster) and these contain SyncedCron jobs doing various background tasks regularly. The server CPUs have recently started getting maxed out and I am  now considering moving all background cron jobs to a separate dedicated server so it does not affect the main app. 

My question is, is it possible to run SyncedCron only on a single server? 
I think there might be 2 ways to do this:
1) On the dedicated server running the same meteor app, have an environment variable set to run Cron jobs: 
```
  job: function() {
    if (process.env.RUN_BACKGROUND_TASKS === ‘true’) {
       // do some task
    }
  }
```
  This will make the Cron jobs to only run on that one server.. (Is there some configuration in SyncedCron which can help me do this?)

2) Create a separate Meteor app which shares the database with the the main app. This app will contain the cron jobs. 

Could this package help in this scenario in some way?

**Comment by tomtom87** [comment]
@niranjans Yes this is totally possible and you are right in your suggestions.

Essentially suggestion 1 or 2 is fine - I normally run cron on the database server itself  so it can just deal with the tasks and get it done fast. I don't have anything else going on just the database and cron running. 

You can add a conditional in your code to check for that via a environmental variable as you suggest.
