### ISSUE TITLE
App crashes upon adding synced-cron

### ISSUE THREAD

**Issue by n8barr** [percolatestudio/meteor-synced-cron#104]
I added synced-cron and my app immediately crashes. Removing the dependency resolves the issue. The stack trace doesn't provide me any clues. Can anyone else make sense of this? Is anyone else experiencing the same thing?

**Stack trace:**
W20160728-09:14:32.369(-4)? (STDERR)          
W20160728-09:14:32.386(-4)? (STDERR) /Users/n8barr/.meteor/packages/meteor-tool/.1.1.4.1qgf5pl++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160728-09:14:32.386(-4)? (STDERR) 						throw(ex);
W20160728-09:14:32.386(-4)? (STDERR) 						      ^
W20160728-09:14:32.390(-4)? (STDERR) ReferenceError: Tinytest is not defined
W20160728-09:14:32.390(-4)? (STDERR)     at Template.hello.greeting (packages/percolate_synced-cron.js:388:1)
W20160728-09:14:32.390(-4)? (STDERR)     at packages/percolate_synced-cron.js:606:4
W20160728-09:14:32.391(-4)? (STDERR)     at packages/percolate_synced-cron.js:674:3
W20160728-09:14:32.391(-4)? (STDERR)     at /Users/n8barr/Google Drive/Sites/panac.io/.meteor/local/build/programs/server/boot.js:222:10
W20160728-09:14:32.391(-4)? (STDERR)     at Array.forEach (native)
W20160728-09:14:32.391(-4)? (STDERR)     at Function._.each._.forEach (/Users/n8barr/.meteor/packages/meteor-tool/.1.1.4.1qgf5pl++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160728-09:14:32.391(-4)? (STDERR)     at /Users/n8barr/Google Drive/Sites/panac.io/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**My app's package versions:**
accounts-base@1.2.0
accounts-password@1.1.1
autoupdate@1.2.1
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
check@1.0.5
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
fastclick@1.0.3
fongandrew:find-and-modify@0.2.2
fortawesome:fontawesome@4.5.0
fourseven:scss@3.2.0
geojson-utils@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
insecure@1.0.3
iron:controller@1.0.8
iron:core@1.0.8
iron:dynamic-template@1.0.8
iron:layout@1.0.8
iron:location@1.0.9
iron:middleware-stack@1.0.9
iron:router@1.0.9
iron:url@1.0.9
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
meteor@1.1.6
meteor-platform@1.2.2
minifiers@1.1.5
minimongo@1.0.8
mobile-status-bar@1.0.3
mongo@1.1.0
npm-bcrypt@0.7.8_2
observe-sequence@1.0.6
ordered-dict@1.0.3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
service-configuration@1.0.4
session@1.1.0
sha@1.0.3
spacebars@1.0.6
spacebars-compiler@1.0.6
srp@1.0.3
templating@1.1.1
tracker@1.0.7
twbs:bootstrap@3.3.5
ui@1.0.6
underscore@1.0.3
url@1.0.4
webapp@1.2.0
webapp-hashing@1.0.3

**Comment by gaiazov** [comment]
I had the same issue when running on Meteor 1.2.1. Upgrading version of meteor fixed it.

Seems like the test file was loading when it shouldn't have been.

**Comment by n8barr** [comment]
Yes, that does appear to be a solution. I updated to Meteor 1.4 and I can add this package without my app crashing.
