### ISSUE TITLE
How to properly handle error in job ?

### ISSUE THREAD

**Issue by sabativi** [percolatestudio/meteor-synced-cron#107]
Hello,

I am wondering how you guys are handling errors in job function.

Taking the README example : 

```
SyncedCron.add({
  name: 'Crunch some important numbers for the marketing department',
  schedule: function(parser) {
    // parser is a later.parse object
    return parser.text('every 2 hours');
  },
  job: function() {
    var numbersCrunched = CrushSomeNumbers();
    return numbersCrunched;
  }
});
```

Suppose that `CrushSomeNumbers()` gets an error what's the best way to handle it so that i can warn users of a problem or at least the developper.

should this be :
```
const CrushSomeNumbers = () => {
    ...
    if (error) {
         return error;
         // or 
         thrown new Meteor.Error()
    }
}
```

**Comment by TheGame2500** [comment]
@sabativi , a try/catch block works best in my experience. In catch just log your error/mail it to yourself if it's a really serious one.

**Comment by sabativi** [comment]
Thanks for your answer, so there is now way to mark the cron as failed or
ok directly ?
If not, do you think it would be easy ? If so i will try to do it and send
a PR.
