### ISSUE TITLE
SyncedCron job not running on Heroku production server

### ISSUE THREAD

**Issue by adamdawkins** [percolatestudio/meteor-synced-cron#11]
Hi, 

This probably isn't a synced-cron bug in itself, but I'd appreciate your thoughts. I have a SyncedCron job that works perfectly in development, but when I push to my server (on Heroku), it never fires. I've tried having the job in `server/jobs/` and moving it to the `bin` directory.

What could be preventing this?

Here's the job itself:

``` coffeescript
SyncedCron.add
  name: 'Import products'
  schedule: (parser) ->
    parser.text('every 24 hours')
  job: ->
    Meteor.call 'import_product_json'

Meteor.startup ->
  SyncedCron.start()
```

**Comment by aj07mm** [comment]
anyone got it working on heroku? @adamdawkins

**Comment by ThadeuLuz** [comment]
There are at least three problems that I can think of when trying to use this tool on heroku.

The first one is that heroku's free dynos need to sleep 6 hours a day I believe. A possible solution is paying, something like Us$ 7 a month and you get one dyno that never sleeps.

The second problem is that this task would probably run once for each active dyno you have. If your task is something like refreshing data on the servers Ram memory or deleting temp files, then no problem. But if it is something like storing things in the database, or making an http request, then (if you have 3 dynos runing) those tasks would run three times each.

The third problem is that the code would be running on Web dynos, and the best option whould be if it was running on worker dynos. Worker dynos receive no http requests and are dedicated to runing your task. If your task is simple then you are fine running them on Web dynos.

I dont have a perfect solution for my case, but I think it will involve heroku scheduler. This add on spaws a work dyno just to run your task.

**Comment by nesbtesh** [comment]
I have a performance cluster in heroku but the cron jobs are not running, did anyone get it working?
