### ISSUE TITLE
Far future jobs don't run – cronHistory only exists after event runs.

### ISSUE THREAD

**Issue by mattlinares** [percolatestudio/meteor-synced-cron#111]
I can make near future (e.g. 1 min) jobs run, but am having problems with jobs that run in a week or so. I want to debug by inspecting the queued tasks, which I thought cronHistory would enable (since it helps sync between processes), but cronHistory items don't appear until after the job has run.

How can I inspect queued processes that haven't run yet to get an idea of when jobs are actually being set up or not? Right now I can't debug why certain tasks are not running.

Thanks

**Comment by spawn-guy** [comment]
"Current" Jobs are stored in Memory. 
if you create Jobs in Runtime look at this issue #80 and remember that cronHistory - is just History.

if your server restarts - you need to re-create runtime jobs

**Comment by ElegantSudo** [comment]
@spawn-guy I don't get it, are you saying that synced-cron's jobs don't persist in the database?

**Comment by JanSchuermannPH** [comment]
@ElegantSudo future jobs are not stored in the database but the memory. If you restart your server, the memory resets and the jobs are scheduled again.

If you had a job that should run "in 1 week", and you restart the server after 5 days, the job will run 1 week after you restarted the server.

the cron history persists in the database up to the TTL you set in the synced cron config.

**Comment by ElegantSudo** [comment]
@JanSchuermannPH so in other words, "every Wednesday at 7:00pm" would work fine, but "in 5 days" would not.

**Comment by TheGame2500** [comment]
Yes
