### ISSUE TITLE
How to set the start of cron job?

### ISSUE THREAD

**Issue by scheung38** [percolatestudio/meteor-synced-cron#114]
parser.text('every 4 hours');

Set the frequency of cron job, but what about the start of the job, can we determine when that 4 hour begins and ends?

**Comment by guidouil** [comment]
I have a `parser.text('every 30 minutes');` and it starts every round hours. I guess for 4 hours it will start at midnight (00:00) and go on...

**Comment by JanSchuermannPH** [comment]
It can be found in the later.js documentation at [http://bunkat.github.io/later/parsers.html#text](http://bunkat.github.io/later/parsers.html#text):

To start the 4 hours not at midnight (default) but let's say at 6 am:

`parser.text('every 4 hours starting on the 6th hour');`
