### ISSUE TITLE
SyncedCron not exported on the server

### ISSUE THREAD

**Issue by Kostronor** [percolatestudio/meteor-synced-cron#116]
Once I try to set a config file, I get an unresolved error. It tells me that SyncedCron is undefined.
And there is no package for it so I can't import it. How can I set my config?

**Comment by MichalW** [comment]
Did you import SyncedCron?
```
import {SyncedCron} from 'meteor/percolatestudio:synced-cron';
```

**Comment by Kostronor** [comment]
I would never have guessed that string 😮 can we add that to the docs?

**Comment by Kostronor** [comment]
@MichalW `Error: Can't find npm module 'meteor/percolatestudio:synced-cron'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?`

You have to use percolate and drop the studio for it to work
