### ISSUE TITLE
Cannot find name 'SyncedCron'

### ISSUE THREAD

**Issue by ryanlion** [percolatestudio/meteor-synced-cron#117]
Hi. 

I have run:  
meteor add percolate:synced-cron

after I add to my server/main.ts

SyncedCron.add({
    name: 'Crunch some important numbers for the marketing department',
    schedule: function(parser) {
      // parser is a later.parse object
      return parser.text('every 0.5 minutes');
    },
    job: function() {
      return 1;
    }
  });
  SyncedCron.start();

when i start the server, it is saying "Cannot find name 'SyncedCron'"

I have tried to import "synced-cron" also doesn't work. Can anyone please help? Thanks

**Comment by ryanlion** [comment]
by the way, my meteor version is Meteor 1.4.2.3

**Comment by hexsprite** [comment]
@ryanlion does it work if you put it in a `main.js` instead of ts?

**Comment by Sornii** [comment]
Can you zip a running example?
