### ISSUE TITLE
Cron job is executed on both instances at the same time

### ISSUE THREAD

**Issue by WayneUong** [percolatestudio/meteor-synced-cron#118]
We have a cron job to send emails that runs once every second, with `Meteor._sleepForMs(2000);` inside to simulate data fetching. Running 2 instances on the same database side-by-side, I almost always get one email sent out by both instances.

<img width="1680" alt="screen shot 2017-03-23 at 3 59 46 pm" src="https://cloud.githubusercontent.com/assets/8436742/24273894/3530ee58-0fe2-11e7-9f2a-1e3f21c3a7ad.png">

**Comment by WayneUong** [comment]
After doing some testing, I find that if the first instance starts a job, and take too long to finish it, the second instance will start the same job.

**Comment by TheGame2500** [comment]
@WayneUong, I expect your cron job fetches some stuff from the db, processes it, and then somehow marks it as processed. I handle race conditions like yours by using findAndModify, marking the fetched doc in question with a flag like { processing : true }. And as a query, I use { processing : {$exists:false}}. That would prevent your second container from grabbing the same item and processing it again no matter how long it takes. To handle errors, just $unset the processing flag.

**Comment by WayneUong** [comment]
@TheGame2500 thanks for your suggestion. I've also explored `findAndModify` but we need to fetch multiple objects from db at once. That's what usually causes the race condition.

**Comment by TheGame2500** [comment]
@WayneUong. Just use while and findAndMofify
