### ISSUE TITLE
Using Upsert in Cron Job

### ISSUE THREAD

**Issue by jkd65** [percolatestudio/meteor-synced-cron#121]
I am running a cron job every 5 minutes that will read tables in a SQL database, and then upsert that data into Mongo Collections.

The purpose is to keep my MongoDB up to date with my SQL Database. This works great in production and the cron job runs perfectly. But, when running this in production, the upserting is not working as intended, which leads me to believe the cron jobs are failing

**Comment by martineboh** [comment]
I am also facing the same issue with my jobs. Whenever the servers restart, previous crons stopped working until you run them again.

**Comment by jkd65** [comment]
I found out my issue. I was running asynchronous functions within the cron job. Because of this, the cron job would finish prematurely, and my upserts wouldn't have time to finish causing weird behavior. The solution was to just make those asynchronous functions synchronous.
