### ISSUE TITLE
SyncedCron doesn't start on server restart.

### ISSUE THREAD

**Issue by martineboh** [percolatestudio/meteor-synced-cron#122]
Hello,
I created several crons to handle some tasks. Runs fine until I make some changes to my codes, this causes Meteor to restart as usual and my crons stopped working. How do I restart those jobs on server restart? Are the jobs stored in some kind of collections with their arguments? Please help. Thanks

**Comment by JonVisc** [comment]
I believe before 1.4 (or 1.3, whenever Meteor added the imports/ directory), you could call:
Meteor.startup() and anything inside that function call, would be initialized once the Meteor had finished starting.
http://docs.meteor.com/api/core.html#Meteor-startup

In newer Meteor, this link about the file structure mentions additional ways: https://guide.meteor.com/structure.html#javascript-structure

**Comment by jkd65** [comment]
Yes @JonVisc reply. I have a cron job file in `./imports/startup/server/cron.js` and in my `./server/main.js/` I have `import './imports/startup/server/cron.js` and it works for me!

**Comment by martineboh** [comment]
Thanks guys! Finally got it working with @JonVisc suggestion.
