### ISSUE TITLE
Meteor code must always run within a Fiber When Called From Async Function

### ISSUE THREAD

**Issue by stolinski** [percolatestudio/meteor-synced-cron#123]
This is being called from inside a method.

```
async function insertNotification({ title, active, body, timer, link, apptId, userId, createdAt }) {
  try {
    const notifId = await Notifications.insert({
      title,
      userId,
      active,
      body,
      timer,
      link,
      apptId,
      createdAt,
    });
    if (timer !== '') {
      SyncedCron.add({
        name: notifId,
        schedule(parser) {
          return parser.recur().on(timer).fullDate();
        },
        job() {
          try {
            notif(userId, {
              userId,
              title,
              body,
            });
            const now = new Date();
            sent({
              _id: notifId,
              sentAt: now,
            });
            SyncedCron.remove(notifId);
            return notifId;
          } catch (error) {
            console.error(error);
            throw new Meteor.Error(500, 'cron error', error);
          }
        },
      });
    }
  } catch (error) {
    throw new Meteor.Error(500, 'insertNotification functions', error);
  }
}
```

**Comment by thsowers** [comment]
I've found that if you are inserting documents into the database (which is what SyncedCron.add does) from an async function like this that you sometimes need to wrap the code in a fiber like so:

```javascript
Fiber(function () {
  SyncedCron.add({
    ...
   })
}).run()
```

you might need to install the npm [fibers](https://www.npmjs.com/package/fibers) package for this to work

**Comment by jehartzog** [comment]
While you could import `fibers`, Meteor includes the `bindEnvironment` method to cover this use case and by wrapping with fibers and maintaining the Meteor environment.

Also, looking at the snippet above by @thsowers , I'm not sure but I don't think you should wrap the `SyncCron.add` method with a fiber, instead you will want to wrap the function that is being called async.

 It's not well documented, but you can see an example [here](https://guide.meteor.com/using-npm-packages.html#bind-environment). Here is a copy paste of the code snippet there:
```
// Inside a Meteor method definition
updateGitHubFollowers() {
  github.user.getFollowingFromUser({
    user: 'stubailo'
  }, Meteor.bindEnvironment((err, res) => {
    // Everything is good now
    Followers.insert(res);
  }));
}
```
