### ISSUE TITLE
Suggestion to improve code for synced-cron-server.js

### ISSUE THREAD

**Issue by si4dev** [percolatestudio/meteor-synced-cron#125]
Suggestion for synced-cron-server.js:
If you change `next = s.next(2, now);` into `next = s.next(1, now + 1001);` then you don't need the extra check:

```
    // minimum time to fire is one second, use next occurrence instead
    if(diff < 1000) {
      diff = next[1].getTime() - now;
      intendedAt = next[1];
    }
```

I choose to add with 1001 to ensure it is later than 1 second (1001 millisecond) probably +1000 should work too

**Comment by TheGame2500** [comment]
Write this as a pull request please.
