### ISSUE TITLE
Launch job at startup

### ISSUE THREAD

**Issue by Farkal** [percolatestudio/meteor-synced-cron#126]
I would like to run all my jobs each hour but also when my server start so is there any option like `on_start`:
```
SyncedCron.add({
        name: 'Change music status',
        schedule: function(parser) {
            return parser.text('every 1 hour');
        },
        on_start: True,
        job: function() {ChangeStatusMusics.changeStatusMusics()}
    });
```
to be able to run the job at the beginning ?

**Comment by thsowers** [comment]
I don't think that functionality is provided in this package, but you might want to take a look at [Meteor.startup()](https://docs.meteor.com/api/core.html#Meteor-startup) which will run each time the server is started

```javascript
Meteor.startup(function(){
  ChangeStatusMusics.changeStatusMusics()
});
```

**Comment by TheGame2500** [comment]
Just write a function which you call on startup and also pass to SyncedCron.add
