### ISSUE TITLE
Job throws buffer.js TypeError

### ISSUE THREAD

**Issue by leosco** [percolatestudio/meteor-synced-cron#127]
Whenever my job in particular is called, I receive this error.
```
SyncedCron: Exception "Example Job" TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:208:11)
    at Function.Buffer.from (buffer.js:85:10)
    at myJob(server/myJob.js:575:34)
    at Object.job (server/myJob.js:614:12)
    at packages\percolate_synced-cron.js:242:26
    at scheduleTimeout (packages\percolate_synced-cron.js:290:7)
    at packages\percolate_synced-cron.js:338:42
    at [object Object].EVp.withValue (packages\meteor.js:1134:15)
    at packages\meteor.js:452:25
    at runWithEnvironment (packages\meteor.js:1188:24)
```
I can't share my code specifically, but it's a pretty large function with a bunch of synchronous API requests, using Meteor's `http` package, that query an API for some stuff, and compare it to contents of my collections. Testing the function normally in a Meteor.method doesn't throw any errors, but it does take about half a minute to finish running. Am I tripping some sort of timeout, are the HTTP calls to blame, what's going on here?

**Comment by TheGame2500** [comment]
@leosco not this package's fault. You, or a package you're using are doing something in 'myJob.js' at line 575 which throws an error. Use a try/catch block for that line, log the stuff you're passing to whatever's going on at line 575 whenever an exception is found. According to the `Buffer.from` [docs](https://nodejs.org/api/buffer.html) the type of the argument must be one of the ones your error says. 

My guess is you're doing something like 
```javascript
const dbDoc = dbCollection.findOne(`query`);
functionWhichUsesBuffer(dbDoc);
```

And the function which uses buffers is not checking that `dbDoc` is defined and an accepted type.

You should start using [check](https://docs.meteor.com/api/check.html). It's neat and spares you lots of frustration.

**Comment by leosco** [comment]
No, you're totally right. I had missed a catch in case the buffer was empty. Sorry for wasting your time 😢

**Comment by TheGame2500** [comment]
@leosco , no worries! Happy coding!
