### ISSUE TITLE
cronHistory Collection

### ISSUE THREAD

**Issue by HaolinWang8** [percolatestudio/meteor-synced-cron#128]
I checked in the server mongo and found that there is history of cronHistory stored in the collection. But it has only 2-3 days history. My app is running for a while. Does it automatically delete the history? If not, will big amount of documents stored in cronHistory will slow down the system?

**Comment by Fudgemaker** [comment]
You can delete the history with a cron job.

// Purge cronHistory after five hours
SyncedCron.add({
  name: 'purgeCronHistory',
  schedule: function(parser) {
    // parser is a later.parse object
    return parser.text('every 5 hour'); // Set the time interval here
  },
  job: function() {
    const cronHistory = SyncedCron._collection;
    cronHistory.remove({}); // Removes all history. Make selections here if needed.
  }
});

**Comment by tomtom87** [comment]
@HaolinWang8 The cron history is persistent so you will want to do log rotation same as you will do for error logging maybe on your nginx.

**Comment by tomtom87** [comment]
@HaolinWang8 The log is persistent unless you are clearing it. Yes if left for a long time and there are many entries generated; it can take up excessive space. You can purge as @Fudgemaker explained though..
