### ISSUE TITLE
How to schedule a one-off job that is executed immediately?

### ISSUE THREAD

**Issue by vfonic** [percolatestudio/meteor-synced-cron#131]
I'm having some issues trying to setup a one-off job that executes immediately.
I want to run a job on server startup.
Following the documentation, this is how I setup my job, but it never runs:

```js
SyncedCron.add({
  name: 'Crunch some important numbers for the marketing department',
  schedule(parser) {
    // parser is a later.parse object
    return parser.recur().on(new Date()).fullDate();
  },
  job() {
    ...
  }
});
```

How can I debug this? What is the proper way to schedule jobs to execute immediately?

`db.cronHistory.find()` returns nothing
  

Console output:
> `SyncedCron: Scheduled "Crunch some important numbers for the marketing department" next run @0`

**Comment by vfonic** [comment]
I think there's something wrong with `.fullDate()`. I think that recurring pattern doesn't create correct schedule (returns 0 instead of next date).

This works, but looks very hackish:

```js
SyncedCron.add({
  name: name,
  schedule(parser) {
    // parser is a later.parse object
    return parser.text('every 5 seconds');
  },
  job() {
    // crunch some numbers
    SyncedCron.remove(name);
  },
});

SyncedCron.start();
```

**Comment by TheGame2500** [comment]
@vfonic why don’t you just use Meteor.startup()?

**Comment by vfonic** [comment]
@TheGame2500 I need the code to run on a single server and it's a potentially long-running code. Not sure is `Meteor.startup()` blocking the rest of execution or not?

**Comment by TheGame2500** [comment]
@vfonic use `Meteor.defer` to prevent blocking
