### ISSUE TITLE
Unhandled duplicate key errors with Meteor 1.7

### ISSUE THREAD

**Issue by oneeman** [percolatestudio/meteor-synced-cron#134]
This has already been filed as https://github.com/percolatestudio/meteor-synced-cron/issues/133, but I'm filing a new issue since that one was closed and the problem hasn't been fixed yet.

The issue is due to Meteor 1.7 having switched from v2 of the node mongo driver to v3.  One of the breaking changes is how errors in bulk writes are surfaced.  See "BulkWriteResult & BulkWriteError" at https://github.com/mongodb/node-mongodb-native/blob/master/CHANGES_3.0.0.md .  As a result, when an `.insert()` call results in a duplicate key error, the error's name has changed from `MongoError` to `BulkWriteError`, and so the handler at https://github.com/percolatestudio/meteor-synced-cron/blob/a82a3569322c0e9cb878de7c3baab94648e0260d/synced-cron-server.js#L215 no longer recognizes it correctly.

A fix which will work with both versions of the mongo driver is to check just the error code, not the error name.  I've done this on my project and confirmed that it fixes the issue.  I will open up a pull request, though I don't know how actively this repo is being maintained.

For those who need to fix this issue without waiting for a new release, see https://forums.meteor.com/t/how-to-replace-an-atmosphere-package-with-own-local-copy/25922 for how to use a local version of the package instead.

**Comment by etyp** [comment]
@TheGame2500 do you know who has atmosphere access?

**Comment by TheGame2500** [comment]
@acomito @etyp @oneeman  fixed by migrating to https://atmospherejs.com/littledata/synced-cron
