### ISSUE TITLE
Compatible with Meteor 1.8?

### ISSUE THREAD

**Issue by medied** [percolatestudio/meteor-synced-cron#138]
My setup is as follows:

```
$ meteor --version
Meteor 1.8.0.2
```

```
$ meteor list
accounts-facebook            1.3.2  Login service for Facebook accounts
accounts-password            1.5.1  Password support for accounts
...
littledata:synced-cron       1.5.1  Allows you to define and run scheduled jobs across multiple servers
...
```

Behavior that I'm getting is that it's simply unresponsive: no logs anywhere, no cron jobs being started. The only thing I can see is that the `cronHistory` collection is created in the db, but stays empty. 

What am I missing? Or is this package simply outdated by now and not compatible with latest Meteor version?

You can see the different attempts I made in [this commit](https://github.com/DemocracyEarth/sovereign/commit/f26e058587e3098002a4326c8b6fe51d9249aac1)

**Comment by TheGame2500** [comment]
@medied you forgot importing cron.js into `/imports/startup/server/index.js`

**Comment by medied** [comment]
Thank you @TheGame2500 👏
