### ISSUE TITLE
Impossible to set certain options

### ISSUE THREAD

**Issue by zol** [percolatestudio/meteor-synced-cron#15]
Certain `SyncedCron.options` (`collectionName`, `utc`) are used immediately after the options definition thus not giving the application author a chance to override them.

**Comment by mrsolo5k** [comment]
It looks like problem has come back after updating to version **1.1.1**. Especially I'm not able to switch off logging which is a little bit annoying, since my job is triggered every 5 seconds.

**Comment by zol** [comment]
@mrsolo5k This is working fine in the example provided (modify it to turn off logs). Please add a reproduction.

**Comment by mrsolo5k** [comment]
You are right, it's working fine. I encountered this issue, because I was updating `SyncedCron.options` and running `SyncedCron.start()` inside the callback of `Meteor.startup` function. Moving the code updating the options outside of `Meteor.startup` solved my problem.
