### ISSUE TITLE
Cannot run jobs due to Mongo duplication error

### ISSUE THREAD

**Issue by johanbrook** [percolatestudio/meteor-synced-cron#25]
Hi! Great package! We use it at [Lookback](https://lookback.io/) for running email jobs for different timezones.

However, this has magically stopped working. From the logs, I read:

```
SyncedCron: Not running "Run Daily Timezone Jobs" again.
```

from [line 134](https://github.com/percolatestudio/meteor-synced-cron/blob/master/synced-cron-server.js#L134) for each time a new job is gonna run. 

The thing is, we're only running the app on one instance, and there cannot be any already existing recordings, due to their unique names and `intendedAt` property (them being indexes).

I even cleared the `cronHistory` collection, but after a couple of hours, it kept logging the duplication message.

Any idea what I'm doing wrong? I've debugged everything up until this.

**Dump**

```
db.cronHistory.find({name: 'Run Daily Timezone Jobs'}).sort({intendedAt: -1})
{ "_id" : "MR3zMKuyCtiYNHDNf", "finishedAt" : ISODate("2014-11-19T09:00:00.038Z"), "intendedAt" : ISODate("2014-11-19T09:00:00Z"), "name" : "Run Daily Timezone Jobs", "result" : null, "startedAt" : ISODate("2014-11-19T09:00:00.001Z") }
{ "_id" : "TeQDcCSukmJRujNRj", "finishedAt" : ISODate("2014-11-19T08:00:00.110Z"), "intendedAt" : ISODate("2014-11-19T08:00:00Z"), "name" : "Run Daily Timezone Jobs", "result" : null, "startedAt" : ISODate("2014-11-19T08:00:00.001Z") }
{ "_id" : "2MwJfZpiCbDs4Wgnp", "finishedAt" : ISODate("2014-11-19T07:00:00.232Z"), "intendedAt" : ISODate("2014-11-19T07:00:00Z"), "name" : "Run Daily Timezone Jobs", "result" : null, "startedAt" : ISODate("2014-11-19T07:00:00.002Z") }
{ "_id" : "t2YvJk5FMSpAEL2ha", "finishedAt" : ISODate("2014-11-19T06:00:01.580Z"), "intendedAt" : ISODate("2014-11-19T06:00:00Z"), "name" : "Run Daily Timezone Jobs", "result" : null, "startedAt" : ISODate("2014-11-19T06:00:00.002Z") }
{ "_id" : "tjz5mxZfnmCa5cw6Q", "finishedAt" : ISODate("2014-11-19T05:00:00.067Z"), "intendedAt" : ISODate("2014-11-19T05:00:00Z"), "name" : "Run Daily Timezone Jobs", "result" : null, "startedAt" : ISODate("2014-11-19T05:00:00.001Z") }
{ "_id" : "84jbCFdbjwYFdnanC", "finishedAt" : ISODate("2014-11-19T04:00:00.057Z"), "intendedAt" : ISODate("2014-11-19T04:00:00Z"), "name" : "Run Daily Timezone Jobs", "result" : null, "startedAt" : ISODate("2014-11-19T04:00:00Z") }
```

**Comment by lowi** [comment]
I have the same issue on my server, I will investigate it.

**Comment by HemalR** [comment]
Hoping anyone on this thread has any guidance from their experiences - This has suddenly started happening to me. Error log:

`errmsg: 'E11000 duplicate key error index: myapp_staging.cronHistory.$intendedAt_1_name_1 dup key: { : new Date(1533419400000), : "Schedule msgs" }'`

I do have an additional field getting indexed , that is the only potential cause I can think of - it is not indexed as a unique field, however, so question: Would the same value (e.g. null), for an indexed field, be causing this?

Thanks in advance for any help regarding this!

**Comment by pagesrichie** [comment]
I'm having the same issue all of a sudden too.. the app was working fine for a while too

**Comment by HemalR** [comment]
Cheers for that @TheGame2500 - My use case was simple enough to find a native JS workaround and bypass Cron for the time being, but it is something that I need to address. Appreciate the info!

**Comment by mephraums** [comment]
I know this is an old issue but in case anyone is experiencing this, I had this issue after deleting the cronHistory collection in the database. It will automatically get created but if the unique key index is not there, this error will happen.
