### ISSUE TITLE
Preventing jobs from running at all?

### ISSUE THREAD

**Issue by SachaG** [percolatestudio/meteor-synced-cron#33]
This may be somewhat of a niche use case, but I'd love to have a way to prevent a job from being scheduled from within the job itself, in order to let the end user enable to disable jobs right from Telescope's web UI. 

In other words, let me `return false` somewhere to prevent the message `SyncedCron: scheduled "scheduleNewsletter" next run @Mon Jan 05 2015 00:00:00 GMT+0900 (JST)` from being logged at all, if that makes sense?

**Comment by zol** [comment]
I feel like this is indeed a niche use case and perhaps could be solved differently. Could the job itself check whether it's disabled and not run accordingly?

**Comment by SachaG** [comment]
The job can do that and effectively not do anything, but the message will still run no matter what if I'm not mistaken?

I'm just worried that it might be confusing for Telescope users to see "scheduled sendNewsletter job" in the logs, even when they've turned the newsletter feature off. 

Not sure if there's another way around that?

**Comment by zol** [comment]
In that case I'd suggest setting `SyncedCron.options.log = false;` and also changing the name of the job to something more descriptive like `attemptSendNewsletter`

**Comment by SachaG** [comment]
Sounds reasonable, thanks :)

**Comment by zol** [comment]
No worries!​
