### ISSUE TITLE
Run job only once or not at all

### ISSUE THREAD

**Issue by pefi1011** [percolatestudio/meteor-synced-cron#35]
Hi Zoltan,

maybe is a bit stupid question, but how can I set a job to run only once?
For example in 7 days from now, run job "remind user" ? And when the time comes I want to check if it's still necessary to remind the user, if not I want to prevent running the job at all.

I appreciate your help, thanks ;)

**Comment by geekyme** [comment]
+1

**Comment by zol** [comment]
This kind of logic should be in the job itself. Schedule a job for 'seven days from now' and within the job itself perform your check and short circuit the rest of the logic in the job if its unnecessary to remind the user at that time.

**Comment by geekyme** [comment]
Sorry I'm a little confused by what you meant by short circuit the rest of the job. 

May I know how do we do that?

**Comment by pefi1011** [comment]
+1

Thanks for replying Zoltan! Could you please give an example for "short circuit the rest of the logic in the job" ?  Is the job going to run n times and stop executing the logic when n=>2 or is not going to run at all 2nd time?

**Comment by zol** [comment]
I was thinking something like:

```
job: function() {
  if (shouldRemindUser())
    remindUser();
}
```

The job will always be executed according to the schedule but if `shouldRemindUser()` is `false`, it won't actually do anything.

Maybe I'm completely misunderstanding your requirements though.

**Comment by pefi1011** [comment]
Yes, I see, thanks ;) ..one more thing is confusing me, can a schedule a job to run "seven days from now" and never again? Or to delete the job when ``shouldRemindUser()`` returns ``false`` for the first time?

**Comment by zol** [comment]
You could remove the job from within itself using `SyncedCron.remove` .

**Comment by pefi1011** [comment]
Alright, thanks Zoltan!

**Comment by geekyme** [comment]
Wat if these jobs are added on the fly, triggered by some Template events ?

Will we still be able to add the jobs and have them terminate themselves after X time ?

**Comment by zol** [comment]
Yeah, you can delete jobs from within themselves.
