### ISSUE TITLE
Meteor Galaxy

### ISSUE THREAD

**Issue by ccorcos** [percolatestudio/meteor-synced-cron#36]
This package doesnt appear to be working for me when using `meteor deploy`. Any work-arounds?

**Comment by zol** [comment]
@ccorcos I don't believe there is a work around - Most free service providers will shutdown your app to conserve CPU when there are no requests happening. This makes it impossible for Synced Cron to run your jobs.

**Comment by ccorcos** [comment]
Bummer!
