### ISSUE TITLE
Unable to drop index

### ISSUE THREAD

**Issue by perminder-klair** [percolatestudio/meteor-synced-cron#38]
Hello,

First of all many thanks for your awesome work.
I have an issue, when I try to drop index by: db.cronHistory.dropIndex({startedAt: 1});
It returns with this error:                                                                   
{ "ok" : 0, "errmsg" : "can't find index with key:{ startedAt: 1.0 }" }   

Any solution / suggestion?

**Comment by perminder-klair** [comment]
Used: db.cronHistory.ensureIndex( { "startedAt": 1 }, { expireAfterSeconds: 3600 } ) 
to modify expire time and worked.

**Comment by zol** [comment]
Hey @perminder-klair is this resolved?

**Comment by perminder-klair** [comment]
Yes it's partially resolved, by using:
`db.cronHistory.ensureIndex( { "startedAt": 1 }, { expireAfterSeconds: 3600 } )` 
instead of `db.cronHistory.dropIndex({startedAt: 1});` as specified in documentation.
