### ISSUE TITLE
control actions from client side

### ISSUE THREAD

**Issue by amitrahav** [percolatestudio/meteor-synced-cron#44]
hey i'm trying to send mails with synced-cron, but i need full control over it on the client side.
is there a reactive way to make list of future actions?

I tried using Meteor.call and return the nextScheduledAtDate function into session but it does not change according to the jobs process .

**Comment by zol** [comment]
Take a look at:

https://github.com/percolatestudio/meteor-synced-cron/blob/master/synced-cron-server.js#L62

You could do something similar to where we call `Later.schedule(schedule).next(1)`, but pass another integer in instead of 1 to get a larger list of future schedules.
