### ISSUE TITLE
Allow error to be retrieved in job

### ISSUE THREAD

**Issue by tagrudev** [percolatestudio/meteor-synced-cron#45]
It would be really nice to get the error available in the job

```coffeescript
  SyncedCron.add
    name: "Get some data"
    schedule: (parser) ->
      parser.text('at 5:00 am')
    job: (error) ->
      if error then return error else return "completed"
```

This would be very useful if you want to provide information why the job has failed. Thanks

**Comment by zol** [comment]
@tagrudev what would call `job(error)` and what would `error` be?
