### ISSUE TITLE
Add support for sending an email on job end

### ISSUE THREAD

**Issue by rbabayoff** [percolatestudio/meteor-synced-cron#47]
Especially useful on errors. Thinking of something like the following json object, using meteor's email package:

```javascript

email: {
  from: ...
  to:
  onDone: true
  onError: true
} 
```

I also noticed there seems to be no support for async jobs, which is easily solved using futures. 

I can work on a PR for both, if needed.

**Comment by zol** [comment]
Thanks for considering this @rbabayoff . I would prefer to keep `synced-cron` core as tight as possible. Both of these features could be implemented as job wrapping utilities so I'd rather not include them in core at this stage. Thanks again!
