### ISSUE TITLE
Adding range to fire job within the range

### ISSUE THREAD

**Issue by Karabi-Choudhury** [percolatestudio/meteor-synced-cron#48]
Hi,

Suppose i have two dates date1= Tue Mar 24 2015 12:25:00 GMT+0530 (IST) and date2=Tue Mar 31 2015 12:25:00 GMT+0530 (IST) and both are future dates.
Now i want my job to fire every day at 12:25 starting from march 24 2015 to march 31' 2015.How can i set the schedule in that case?

Thanks,
Karabi

**Comment by zol** [comment]
@Karabi-Choudhury . You should schedule your job to start on 24th March and within the job check if you've reached March 13, then call `SyncedCron.remove` from within the job itself to prevent it from running again.

**Comment by Karabi-Choudhury** [comment]
How can i check for the date?
Do i check it in schedule or job? Can you provide a sample snippet

**Comment by zol** [comment]
Just check the current time from within the job.

**Comment by Karabi-Choudhury** [comment]
My job runs only once .I am getting this error once the job runs for the first time 
" error [Error: Cannot call method 'getTime' of undefined]".
Is it expecting recurring job always? How can i catch this eror?

**Comment by zol** [comment]
You're trying to call a method on an undefined variable. Try using `meteor debug` to help track down what it is.

**Comment by Karabi-Choudhury** [comment]
i have scheduled my job and for some case my server restarts. My job is lost.Can this be prevented?

**Comment by zol** [comment]
Jobs aren't persistent in Synced-Cron, they need to be defined programatically.
