### ISSUE TITLE
comparing scheduled time and current time

### ISSUE THREAD

**Issue by jamauro** [percolatestudio/meteor-synced-cron#50]
Hi,

I've created a few scheduled messages and am using parser.text so that I can say something like "at 10:00am".

Basically I want to have a logic check where I compare the scheduled date and time and the current time, and then take an action. What's the best way to access the message's scheduled date and time? 

Thanks,
John

**Comment by jamauro** [comment]
I'm basically trying to follow this: http://richsilv.github.io/meteor/scheduling-events-in-the-future-with-meteor/

**Comment by zol** [comment]
Try this from within the job: https://github.com/percolatestudio/meteor-synced-cron/commit/9edeb32915782b55fec119e16f1e40dfbfd81ca6
