### ISSUE TITLE
some options work in Meteor.startup, some do not

### ISSUE THREAD

**Issue by chrisbutler** [percolatestudio/meteor-synced-cron#58]
it makes sense why, i guess... when i set a custom logger and `utc: true` AND call `start()` in the same `startup` block, the logger works but the time setting is ignored

i've been trying to figure this out in the background for weeks, and it finally hit me after reading this comment: https://github.com/percolatestudio/meteor-synced-cron/issues/15#issuecomment-72697503

i've never run into this issue with other packages... is it common, or something that can be refactored, or should it at least be called out in the docs?

**Comment by zol** [comment]
When you call `start()`, the settings are used to initialize other dependent code. It's not really practical to re-init this other stuff after a settings change. For this reason, we utilize the fact that a `startup(...)` block runs after code outside it to call `start()` ensuring that you have a chance to make any requisite changes to the settings beforehand.

I'd be happy to accept a PR that makes this clearer in the docs.
