### ISSUE TITLE
cron job stopped running, had to restart meteor

### ISSUE THREAD

**Issue by rkstar** [percolatestudio/meteor-synced-cron#59]
i had a cron job running once per second, it watches a mongo collection and executes any commands it finds in there that match its criteria.  it was running fine for several weeks and then it just stopped.  when i restarted my meteor app it came online again.

not sure what logs might help with troubleshooting this, but i have access to everything.  please help!

**Comment by zol** [comment]
I can't fix this without a reproduction. You could try to use `sinon` to speed up time and reproduce the issue that way.

**Comment by KristerV** [comment]
what is this `sinon` thing? Atmosphere shows some spy stuff, not sure what that is. So how do you speed up time?

**Comment by zol** [comment]
`sinon` is a library used to assist in testing. Read up on what mocks/spies do within the testing concept. You can use `sinon` to manipulate time in order to test functionality in your app that's time dependent.
