### ISSUE TITLE
Every second, have intended_at by the beginning of the second

### ISSUE THREAD

**Issue by dcurletti** [percolatestudio/meteor-synced-cron#62]
Hi there-

I'm using a time series architecture for my db and I would like to run a job at the beginning of every second.  I see that in my cronHistory collection the jobs are running correctly 

```javascript
{
	"_id" : "yAN2jN5aT4HgGQPcY",
	"intendedAt" : ISODate("2015-09-22T20:21:54Z"),
	"name" : "Minute Valuation",
	"startedAt" : ISODate("2015-09-22T20:21:54.693Z"),
	"finishedAt" : ISODate("2015-09-22T20:21:54.720Z"),
	"result" : null
}
```

but some of the writes are not going through.  I believe this is due to my schedule function 

```javascript
  schedule: function(parser) {
    return parser.recur().every(1).second();
  }
``` 

Is there a way for me to make sure that the job gets started at the start of every second?  ie. The 'startedAt' is closer to ```ISODate("2015-09-22T20:21:54.000Z").```

 It could be that this is already happening and that the job itself is not performant and is slowing down the queue. 

Thanks!

**Comment by zol** [comment]
Hi @dcurletti - I don't think Later.js (which synced-cron is built on top of) supports sub-second scheduling.
