### ISSUE TITLE
Question About Multiple Servers

### ISSUE THREAD

**Issue by deejross** [percolatestudio/meteor-synced-cron#63]
The description says this works across multiple processes, but can it work with multiple Meteor servers running the same code? Looking through the source, I don't see where collection.find() is ever used; it seems this package only inserts and updates jobs but never reads what jobs are stored in the collection.

Thank you for any clarification you can provide.

**Comment by zol** [comment]
@deejross - The package uses it's collection to synchronize between servers kind of like a [semaphore[(https://en.wikipedia.org/wiki/Semaphore_(programming)). It doesn't need to read from the collection as a failed insert signals that another server is already executing the job at the given time.
