### ISSUE TITLE
syncedCron.start() is not running jobs again after restart of Meteor

### ISSUE THREAD

**Issue by JoarSvensson** [percolatestudio/meteor-synced-cron#67]
When restarting the Meteor server locally and also when running Meteor as an Node.js application using Supervisor on Debian 8 server, previously scheduled jobs are not activated and run again.

If I add a new scheduled job, the new job will work, but the previous jobs will not run. At restart, same procedure again.

I have placed the syncedCron.start() in a lib.js file inside a (Meteor.isServer) statement, should it rather be within a Meteor.startup statement?

**Comment by JoarSvensson** [comment]
Now tried both within the Meteor.startup statement, as shown in the examples, and outside it, but the behaviour is the same. Is this an issue or do the documentation need to be clarified a bit?

**Comment by JoarSvensson** [comment]
I found out after more digging around, that the previous scheduled jobs are not saved and needs to be readded in a startup function. My suggestion is we add something about this in the documentation. Thanks anyway for a great package!

**Comment by sun-trilogy** [comment]
@JoarSvensson how did you manage to re-add the previous scheduled jobs at startup?

**Comment by sunlee-newyork** [comment]
@JoarSvensson how did you manage to re-add the previous scheduled jobs at startup?

**Comment by JoarSvensson** [comment]
Meteor.startup(function () {
    // Readd all saved jobs from collection 
    Jobs.find().forEach(function(job) {
      try {
        SyncedCron.add({
          name: job._id,
          schedule: function(parser) {
            // parser is a later.parse object
            return parser.cron(job.schedule);
          },
          job: function() {
            var result = fuctionToRun(this.name);
            return result;
          }
        });
      } catch(error) {
        Log.error(error);
      }
    });

    // Start cron process
    SyncedCron.start();

  });

**Comment by sunlee-newyork** [comment]
@JoarSvensson I see. Are you manually storing jobs in the Jobs collection, or is this a config that comes with `synced-cron`? And also, how is the `functionToRun` being revitalized after startup? I'm having a hard time understanding how the job functions are stored persistently and unearthed after each startup.

**Comment by JoarSvensson** [comment]
The jobs are just stored with what ever fields you might need. The most important is the later.js parse string, to set when your job should run. The function being called in my example is the same for all jobs. The function performs any logic you like, e.g updating another collection or calling an API. You need to define your own function and call it on rescheduling like I do.

**Comment by sunlee-newyork** [comment]
Oh, gotcha. I'm dynamically generating one-off jobs with dynamically defined functions for each, so I guess it wouldn't be a solution in my case...

**Comment by sunlee-newyork** [comment]
@JoarSvensson thank you by the way for your help!
