### ISSUE TITLE
Jobs running twice

### ISSUE THREAD

**Issue by queso** [percolatestudio/meteor-synced-cron#70]
I am having an issue where a job is running twice on Crater.io for sending the newsletter. I checked the cronHistory table and I only see one entry, but now that I have two app processes (differenti boxes, but timezones and date/time stamps are in sync) it is still running twice.

HALP?

**Comment by zol** [comment]
Hey. Where is your app hosted? I'm afraid I only have experience running on AWS and Galaxy, where synced-cron works. Could you help debug? The package is quite simple - you could add some logging here for `jobHistory` : https://github.com/percolatestudio/meteor-synced-cron/blob/master/synced-cron-server.js#L203 . If the `intentedAt` field is different between app processes, this will cause the job to run twice. If that's the case, we can figure out where the discrepancy comes from.

**Comment by queso** [comment]
Digital ocean. Sure, I can turn on debugging and take a look



—

**Comment by queso** [comment]
Hmm, the problem didn't occur last night, is it possible that the first
night the unique index was trying to write at the same time and no error
occurred, perhaps?

**Comment by zol** [comment]
I'm not sure. This is quite a mature package so I would be surprised if there was an obvious bug lurking that wasn't biting a lot of folks but you never know...
