### ISSUE TITLE
Old job still running after redeploying app

### ISSUE THREAD

**Issue by dkoo761** [percolatestudio/meteor-synced-cron#72]
I'm not sure if this is the correct behaviour or not:

I used SyncedCron.add() to add a job and then SyncedCron.start() to schedule it. Then deployed the app.

A few weeks later I decided to remove the job so I removed the SyncedCron.add() line from my server startup file (but kept the SyncedCron.start() since I have other cron jobs I need to run). When I redeployed the app, lo and behold the job that I removed was still running on the old schedule. So I'm wondering what the best practice is for removing old jobs since they seem to persist across deployment?

I also had a case where I changed the schedule of a synced-cron job (but didn't call stop() or remove() before deploying) and after deploying I discovered I had the job running on BOTH schedules (the old one and the new one).

I see there's a SyncedCron.stop() and a SyncedCron.remove() so I'm wondering how to combine these with start() and add() into a pattern that works in all 3 of these cases:

1) adding a new cron job
2) changing the schedule of an existing cron job
3) removing a cron job

Here's a simplified version of what I'm currently doing:

```javascript
srvScheduleService = (function () {
    var jobs = {
        WEEKLY_UPDATE: {
            name: 'Process weekly update if it is the appropriate time to do so for each city',
            schedule: function (parser) {
                return parser.text('every 10 minutes');
            },
            job: function () {
                return srvLadderService.processWeeklyUpdate();
            }
        },
        PROCESS_PAYMENTS: {
            name: 'Process monthly payments for users with billing day of month set to today',
            schedule: function (parser) {
                return parser.text('at 8:30 am'); // 12:30am PST or 1:30am PDT
            },
            job: function () {
                return srvMembershipService.processDailyBilling(1);
            }
        }
    };

    return {
        init: function () {
            SyncedCron.config({
                log: true,
                logger: null,
                collectionName: 'cronHistory',
                utc: true,
                collectionTTL: 2592000
            });
            SyncedCron.start();
            if (environmentHelper.isProduction()) {
                SyncedCron.add(jobs.WEEKLY_UPDATE);
                SyncedCron.add(jobs.PROCESS_PAYMENTS);
            }
        }
    };
}());
```

And then in /server/startup.js:
```javascript
Meteor.startup(function () {
    srvScheduleService.init();
});
```

Many thanks,
Dave

**Comment by dkoo761** [comment]
PS. I'm running on Modulus for hosting if that helps at all. I'm also wondering if maybe an application crash was the cause of the orphaned cron jobs (if they aren't supposed to persist across deployments). 

The funny thing is the logging output from the old cron jobs doesn't show up in the server console so the only way I discovered they were still running was by checking the cronHistory collection because I was getting a Mongo duplicate key error (ie. the console message "SyncedCron: Not running blah blah job again"). At first the duplicate key error didn't make sense since I currently only have a single instance of my application but once I realized I had these orphaned cron jobs running the duplicate key error made sense since I had an old job and a new job both running at the exact same time and with the same name.

**Comment by dkoo761** [comment]
Looks like I have an orphaned application instance running that I have no way of accessing but that is still running synced-cron and sending emails lol. Have submitted a support request to Modulus to help me shut it down. Who would have thought? Ha.

**Comment by zol** [comment]
I've heard of this problem happening on modulus from others as well.
