### ISSUE TITLE
Disable console log

### ISSUE THREAD

**Issue by bitomule** [percolatestudio/meteor-synced-cron#8]
I've a cron that runs "every 1 seconds" so it prints tons of messages on terminal. Is there a way to disable this logs?

**Comment by benjamin79** [comment]
Should this work now? I use your example and set log:false, but still get logs to the console.

**Comment by n8ores** [comment]
was this ever done ? (removing the logs)

**Comment by weeger** [comment]
+1

**Comment by mttstt** [comment]
+1

**Comment by zreiby** [comment]
+1

**Comment by rdrgn** [comment]
Maybe this has already done. Try to add this script to your meteor app.

```js
import { SyncedCron } from 'meteor/percolate:synced-cron';

SyncedCron.config({
	log: false,
});
```

It don't work in or after `Meteor.startup()`.

**Comment by MichelFloyd** [comment]
I ended up setting `SyncedCron.options.log = false;` as I got errors with `SyncedCron.config`

**Comment by TheCodeLord** [comment]
If any of the above does not work or you, I use this code in Meteor.startup():

```
function cronLogger (opts) { }

SyncedCron.config({
    log: false,
    logger: cronLogger
});

````

Here I set log to false and also place an empty function for logging (if you place a console log in "cronLogger"  it will log it on each cron iteration).
