### ISSUE TITLE
Cron job sometimes running too soon

### ISSUE THREAD

**Issue by BeSports** [percolatestudio/meteor-synced-cron#82]
Sometimes, my cron job is executed a few ms before it should actually execute. This makes the intended operation not going through, because it checks if a certain object's start_date is in the past.

```
{ 
    "_id" : "j5nLGGxXNyqwtx43S", 
    "intendedAt" : ISODate("2016-03-24T16:30:00.000+0000"), 
    "name" : "Tournament starter", 
    "startedAt" : ISODate("2016-03-24T16:29:59.977+0000"), 
    "finishedAt" : ISODate("2016-03-24T16:29:59.987+0000"), 
    "result" : null
}
```

**Comment by tomtom87** [comment]
@BeSports Please can you make your intended operation have a tolerance of a few ms to allow for this delay? Would this create too much of  a problem, it sounds like you have a race condition. 

Hope you can fix it by increasing a tolerance margin...

**Comment by BeSports** [comment]
@tomtom87 That was originally my plan, but I changed the behaviour to do a one-time cron job at a specific time which seemed to have solved it. Sorry for not updating it sooner!
