### ISSUE TITLE
Package fails with 1.2

### ISSUE THREAD

**Issue by dnish** [percolatestudio/meteor-synced-cron#85]
ReferenceError: Tinytest is not defined
    at Template.hello.greeting (packages/percolate_synced-cron/synced-cron-tests.js:15:1)

**Comment by mroftalp** [comment]
I have the same issue. Shouldn't it be added as a dependency when installed?

**Comment by vimes1984** [comment]
as do I...

**Comment by admeister** [comment]
+1

**Comment by vimes1984** [comment]
I actually moved it into the packages folder and ripped out tiny tests for now, if anybody needs a help doing that I'd be happy to lend ahand.

**Comment by margono13901** [comment]
@vimes1984 need help removing tiny tests

**Comment by vimes1984** [comment]
one min I'll fork this repo, in the mean time create a folder in your project root called packages and in there create a folder called   percolate_synced-cron

**Comment by vimes1984** [comment]
clone this repo into the " percolate_synced-cron" folder: https://github.com/vimes1984/meteor-synced-cron so the files are in the root of that folder and it should run just fine :D

**Comment by lorensr** [comment]
I can confirm that this package `v1.3.1` is broken on Meteor `1.2.1`. Fixed by `meteor add percolate:synced-cron@=1.3.0`

@zol

**Comment by vimes1984** [comment]
<-- This is the correct way to solve this :D

**Comment by zol** [comment]
@lorensr has the correct fixed. I just released version 1.3.2 that depends on Meteor 1.3 but unfortunately that won't solve the problem for v1.3.1

**Comment by sergeant-q** [comment]
So does this mean I can no longer use this package with Meteor 1.2?

**Comment by lorensr** [comment]
You can, by telling meteor to use an old version of the package. See
my add command
above

**Comment by sergeant-q** [comment]
@lorensr muchas thanks you senor!
