### ISSUE TITLE
How to check if jobs are started

### ISSUE THREAD

**Issue by xauxatz** [percolatestudio/meteor-synced-cron#86]
Is it possible to check if jobs are paused or running?
If SyncedCron.start() is called multiple times, will the jobs be added more than once?

**Comment by tomtom87** [comment]
A few ways I use are `console.log` to trace output, if I needed to query a cron status I would use a session variable and check the contents. To get more complicated you could save strings or append to an array so as to know various status or timeline of activity. 

Regarding `SyncedCron.start()` As far as I know - no. It will just start the cron again. Not really sure what you want to achieve with this.
