### ISSUE TITLE
Is there a way to start a specific job by it's name?

### ISSUE THREAD

**Issue by TyGoss** [percolatestudio/meteor-synced-cron#87]
I'm trying to start and stop multiple jobs, and when I run start, it starts them all. Is there any way to only start a specific job based on the jobs name?

**Comment by tomtom87** [comment]
@TyGoss To do this you should use a `Session` flag so that your cron is running all the while but you can turn on / off the flag to start the specific part of the cron you wish to enable. 

There is no function in synced-cron to explicitly start one task yet, so I just use a boolean.

e.g

```
// in server
Session.set 'doCheck', true

// in cron task
 job: () -> 
   defaultOutput = 'N/A'
   check = Session.get 'doCheck'
   if check 
     numbersCrunched = CrushSomeNumbers();
     return numbersCrunched;
  else 
     return defaultOutput

```
