### ISSUE TITLE
How to check when a job last ran from within the job funciton?

### ISSUE THREAD

**Issue by brylie** [percolatestudio/meteor-synced-cron#89]
We want to run a function periodically, that checks for recent changes from a remote host. The function should only request changes since the last time it ran, so that we don't get back unnecessary data. 

How can a SyncedCron job look for the last time it ran (e.g. create a `lastRanAt` variable)?

# Example
One possible example would resemble a collection helper:

```js
SyncedCron.add({
  name: 'Do something',
  schedule: function(parser) {
    // parser is a later.parse object
    return parser.text('every 2 hours');
  },
  job: function() {
   // Get reference to current cron job
   const cronJob = this;

  // Get date cron job last ran
  const lastRun = cronJob.lastRun();
  }
});
```

# Possible solution
```js
SyncedCron.add({
  name: 'Do something',
  schedule: function(parser) {
    // parser is a later.parse object
    return parser.text('every 2 hours');
  },
  job: function() {
    // Get the log item for the last time this job was run
    const lastRun = cronHistory.find({
      name: "Do something"
    }, 
    {
      sort: {
        finishedAt: -1
      },
      limit: 1
    }).fetch();

    console.log(lastRun);
  }
});
```

**Comment by tomtom87** [comment]
Use `Session` to create a last run at, or like you suggest use a collection as a reacrtive object and insert / find to keep track.
