### ISSUE TITLE
TTL not working in any version

### ISSUE THREAD

**Issue by cpalanzo** [percolatestudio/meteor-synced-cron#93]
I see my cronHistory file size growing continuously - even in older Meteor 1.1 applications even though collectionTTL was left at 172,000 (2 days). 

I updated to the latest version on a local Meteor 1.3 copy of the app and set collectionTTL to 90 for testing. It is still NOT being honored - even if I remove the index by hand as suggested:
db.cronHistory.dropIndex({startedAt: 1}) and restart the local app.

Any ideas how to debug and fix this?

Current config is:
`SyncedCron.config({
    // Log job run details to console
    log: false,

```
// Use a custom logger function (defaults to Meteor's logging package)
//logger: null

// Name of collection to use for synchronisation and logging
collectionName: 'cronHistory',

// Default to using localTime
utc: false,

/*
  TTL in seconds for history records in collection to expire
  NOTE: Unset to remove expiry but ensure you remove the index from
  mongo by hand

  ALSO: SyncedCron can't use the `_ensureIndex` command to modify
  the TTL index. The best way to modify the default value of
  `collectionTTL` is to remove the index by hand (in the mongo shell
  run `db.cronHistory.dropIndex({startedAt: 1})`) and re-run your
  project. SyncedCron will recreate the index with the updated TTL.
*/
collectionTTL: 90
```

  });`

**Comment by tomtom87** [comment]
Please try `Meteor reset` to start from a fresh db and try again from there, sometimes I get these odd issues and have to reset my db. Not a great answer I know but it got me through the issue and paid...

**Comment by amanagarwal2189** [comment]
setting it to 90 wont work because minimum is 300 as per the code. late message though. setting ttl doesnt work though!!

**Comment by tomtom87** [comment]
@amanagarwal2189 have you updated the index and rebuild the db? This is a required step. Please double check the code.

**Comment by amanagarwal2189** [comment]
So I realized that none of my config options are getting set. This makes me think whether I am setting SyncedCron.config at the correct place. 
Currently, SyncedCron.config() is called in one of the methods which are invoked during the startup of meteor application. Is there any other way to do it?
