### ISSUE TITLE
Turn of logging for certain events

### ISSUE THREAD

**Issue by BradRyan** [percolatestudio/meteor-synced-cron#94]
I have some jobs that run frequently that I'd like to turn logging off for, but leave on for the other scheduled jobs.  It would be nice to pass a `log: false` option with the job.  Is there anyway to accomplish this?  The only way I can think of would be to parse the job name out of the `opts.message` using  the logger config option.

**Comment by BradRyan** [comment]
I guess for now I'll probably turn logging off and add my own logs in the specific job functions.  If there's an alternative I'd be interested.

**Comment by fabyeah** [comment]
+1

**Comment by generalleger** [comment]
+1

**Comment by tomtom87** [comment]
+1

**Comment by bduff9** [comment]
+1

**Comment by mikkelking** [comment]
I think logging should be off by default, as I don't want the output in my console, or I want to at least be able to control it.

**Comment by mttstt** [comment]
+1

**Comment by Sornii** [comment]
I have a pull request to this
#119

**Comment by todda00** [comment]
I added a custom logger function, and only are logging warn and error levels, but then I looked at the code and info is being used exclusively. I think if at the minimum the message which are errors would use the correct level (log.error) instead of log.info, the custom logger function would suffice the way it is. Here is my implementation:

```
import { Log } from 'meteor/logging';

const CustomLogger = (opts) => {
  const { level, message, tag } = opts || {};
  // Do not log info or debug, only warn and Error
  if (level !== 'warn' || level !== 'error') return;
  Log[level]({ message: `${tag}: ${message}` });
  return;
};

SyncedCron.config({
  logger: CustomLogger,
});

```

**Comment by TheGame2500** [comment]
This should now work at https://atmospherejs.com/littledata/synced-cron
