### ISSUE TITLE
How do I use it with meteor 1.3

### ISSUE THREAD

**Issue by bevinhex** [percolatestudio/meteor-synced-cron#96]
As I understand Meteor 1.3 is more like 2.0 version, not much compatible with previous versions, as the topic says how do I use it with 1.3, it seems nothing exported out.

**Comment by adrianbadarau** [comment]
@bevinhex It does not matter if nothin is exported, the autoloader in meteor 1.3 still works.
All you have to do is add the package as usual with the meteor add percolate:synced-cron command.
After that I recommend you create a separate file on the server part of your app and add define the cron logic there.
To get it to work you need to add the `SyncedCron.start()` method in startup on the server only.

**Comment by bevinhex** [comment]
@adrianbadarau If what you saying is true, by writing the code below:
```
import React from 'react';
import {render} from 'react-dom';
import {Meteor} from 'meteor/meteor';
import App from './App.jsx';
import {Items} from '../api/items.js';

Meteor.startup(()=>{
	render(<App/>,document.getElementById('render-target'));

	SyncedCron.add({
		name:'test cron',
		schedule:function(parser){
			return parser.text('every 3 seconds');
		},
		job:function(){
			let now = new Data();
			let startData = now - 10000;
			Items.remove({createdAt:{$gte:startDate}});
		}
	});
	SyncedCron.start();
});
```
I shouldn't get ```ReferenceError: SyncedCron is not defined```

**Comment by bevinhex** [comment]
Oh , I found it! I wrote the cron job on client side, simply moving the code into 'server/main.js' fixed it. I got to remember cron job is only available for server side.
