### ISSUE TITLE
Cron run at specific timezone and time.

### ISSUE THREAD

**Issue by garysxn** [percolatestudio/meteor-synced-cron#97]
Using Meteor 1.2 I need to change the timezone 'America/Chicago'. I have tried:
SyncedCron.config({ 
   // Default to using localTime
    utc: true // ( 'America/Chicago')
});
SyncedCron.config({
    utc: false, (true/false both)
    timezone: 'America/Chicago'
});
and also in

SyncedCron.add({
    name: ....
    timezone: 'America/Chicago',
    .........
});
But no luck.

**Comment by adrianbadarau** [comment]
@garysxn The package does not currently support timezones.
There is a opened issue #74  regarding this so if you want you can help complete the pull request and then get timezone support.
